### ISSUE TITLE
There is no method that returns all textures (including unregistered)

### ISSUE THREAD

**Issue by Hornflakes** [sketchfab/viewer-api#7]
### Issue
- there is currently no API method that returns **_ALL_** textures
- the only method is `getTextureList( [callback] )` and it returns only the registered textures

### Context
I'm building a configurator for a model that the **user constantly adds textures to**. The user wants to be able **to add textures** by using the **Edit 3D Settings** action on the **model** on **Sketchfab**.

The configurator should require **no further action from the developer** after creation, therefore the `getTextureList` method is lacking because it only returns the registered textures (the ones **the user sets** with the **Edit 3D Settings** action).

---
At the moment the only way of configurating is by showing/hiding nodes and that means you should have multiple nodes in the model for different 2D textures that apply to the same object.

A workaround is adding textures after API start yet that needs further developer action or a CMS solution whenever the user wants to add new textures.

### Solution
A method that returns all the textures (both registered and unregistered).

**Comment by PadreZippo** [comment]
Hi there,

This is by design. For performance and bandwidth purposes, the viewer embed will not load textures that are not registered (i.e. used by a material), so there is no way for the Viewer API to return them because they are not there.

I'm afraid we have no plans to change this behavior. I'd recommend using one of these other methods to build your configurator:

https://help.sketchfab.com/hc/en-us/articles/14493050096913-Workflows-for-configuring-materials-and-textures-in-the-Viewer-API

**Comment by Hornflakes** [comment]
Thank you very much for the quick reply and the info!
